#include <stdio.h>
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <debug.h>
#include <loadfile.h>
#include <sio.h>
#include <dirent.h>
#include <malloc.h>
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#define GM_IF ((vu32 *)0x1F801450)
#define GM_IOP_TYPE (0x80000000)

extern char	patch_bin[]; //Generated by bin2s. 
extern u32	size_patch_bin;

//TODO: pre-reverse with bin2s if it can
#define REWEN(x) ((((x) >> 24) & 0xFF) | (((x) & 0x00FF0000) >> 8) | (((x) & 0x0000FF00) << 8) | ((x) << 24))

#define IOP_BASE_ADDR     0xBC000000
#define PATCH_INSTR_ADDR  0xBCA14000
#define PATCH_BASE_ADDR   0xBCA14004
#define PATCH_BRANCH_ADDR (IOP_BASE_ADDR + 0xa07434)

#ifdef BUILDING_LIB //library
#define PRINTF(x...) printf(x)
#define PRINTF_INIT()
#define ENTRY() load_patch()
#else //standalone ELF
#define PRINTF_INIT() init_scr()
#define PRINTF(x...) scr_printf(x)
#define ENTRY() main()
#endif

int ENTRY()
{
    SifInitRpc(0);
    SifLoadFileInit();

    SifIopReset("", 0);
    while (!SifIopSync()) {};
    PRINTF_INIT();
    PRINTF("\tPPC Patch loader by qnox32\n"
           "\tCompiled "__DATE__"\n"
           "\t\tpatch size: 0x%x\n"
           "\t\tpatch base address: 0x%x",
           size_patch_bin,
           PATCH_BASE_ADDR
           );
    
    if ((*GM_IF & GM_IOP_TYPE) == 0)
    {
        PRINTF("\t\tCONSOLE IS NOT DECKARD.\n");
        nanosleep((const struct timespec[]){{4, 0}}, NULL);
        return 1;
    }

    PRINTF("\t\tapplying patch...\n");
    DI();               //disable interrupts on EE
    ee_kmode_enter();   //enter kernel mode 

    //load patch into memory
    for (int i = 0; i < size_patch_bin; i++) {
        *(vu8*)(PATCH_BASE_ADDR + i) = patch_bin[i];
    }

    //backup original instruction
    u32 original_instr = *(vu32*)(PATCH_BRANCH_ADDR);

    //copy original instruction to backup addr
    *(vu32*)(PATCH_INSTR_ADDR) = original_instr;

    //place branch instruction to patch    
    *(vu32*)(PATCH_BRANCH_ADDR) = 0x0640a148; //ba 0xa14004

    ee_kmode_exit();
	EI();
    DPRINTF("patch applied!\n\t\tOriginal instruction 0x%x\n", original_instr);
    FlushCache(0);
    FlushCache(2);

    PRINTF("Rebooting IOP\n");
    //reset IOP to trigger branch / patch
    SifIopReset("", 0);
    while (!SifIopSync()) {};
    PRINTF("Done!\n");
    nanosleep((const struct timespec[]){{2, 0}}, NULL);

    
    return 0;
}


